__author__ = 'Danny de Snoo'

import platform

# Defineerd de Credits() functie
def Credits():
    print(" ")
    print("---------------------------------------------------------------------------------------")
    print(" ")
    print("   Command_ OS")
    print(" ")
    print("   MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
    print("   MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
    print("   MMMMMMMMMMMMMMMMMNdy++/:--.``...-:/+shNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
    print("   MMMMMMMMMMMMMdo/.                      oMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
    print("   MMMMMMMMMMmo.                          +MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
    print("   MMMMMMMMh-                             +MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
    print("   MMMMMMN/                               +MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
    print("   MMMMMy`                  .-:///:-.     +MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
    print("   MMMMs                .odNMMMMMMMMMMdy/`+MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
    print("   MMMd               :dMMMMMMMMMMMMMMMMMMmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
    print("   MMN.              sMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
    print("   MMo              sMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
    print("   MM:             -MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
    print("   MM`             +MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
    print("   Mm              oMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
    print("   MN              :MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
    print("   MM-             `mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
    print("   MM+              -MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
    print("   MMm`              -dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
    print("   MMMh                /hMMMMMMMMMMMMMMNh+sMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
    print("   MMMMs                 `:+yhhdddhyo/-   +MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
    print("   MMMMMd.                                +MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
    print("   MMMMMMMo                               +MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
    print("   MMMMMMMMmo.                            +MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
    print("   MMMMMMMMMMMd+`                         +MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
    print("   MMMMMMMMMMMMMMmho/.              `-:+ymMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
    print("   MMMMMMMMMMMMMMMMMMMMMNmddhhhdddyyyyhNMMMMMMmhyyydMMMMMMMMMdhmMMMMMMMMMMMMMMMMMMM")
    print("   MMMMMMMMMMMMMMMMMMMMMMMMMMMMm/       -hMMy.  ..` MMMMMMMM+   hMMMMMMMMMMMMMMMMMM")
    print("   MMMMMMMMMMMMMMMMMMMMMMMMMMMm`  /mMNo   yM.  -dNMNMMMMMMMMNsoyMMMMMMMMMMMMMMMMMMM")
    print("   MMMMMMMMMMMMMMMMMMMMMMMMMMMy   dMMMM`  +Md:`   .+NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
    print("   MMMMMMMMMMMMMMMMMMMMMMMMMMMm   +NMMy   yMNMMmy.  /MMMMMMMMhymMMMMMMMMMMMMMMMMMMM")
    print("   MMMMMMMMMMMMMMMMMMMMMMMMMMMMh-   ``  .yMM.`-:-  `hMMMMMMM+   hMMMMMMMMMMMMMMMMMM")
    print("   MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmysosydMMMMdysosydMMMMMMMMMNsoyMMMMMMMMMMMMMMMMMMM")
    print("   MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMs::::::::oMM")
    print("   MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
    print("   MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
    print("   MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNMNMNNM")
    print("   MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+::+/+-hM")
    print("   MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmd+:ymM.sMM")
    print("   MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmNNMMMmNMM")
    print(" ")
    print("   OS Version: Alpha 1.0,  Released on: British: 5/27/2020")
    print("                                       American: 27/5/2020")
    print(" ")
    print("---------------------------------------------------------------------------------------")
    print(" ")
    print("   System     : ", platform.system())
    print("   Node       : ", platform.node())
    print("   Release    : ", platform.release())
    print("   Version    : ", platform.version())
    print("   Machine    : ", platform.machine())
    print("   Processor  : ", platform.processor())
    print(" ")
    print("---------------------------------------------------------------------------------------")
    print(" ")
    print("   Command_ OS is a project by Danny de Snoo, Github: https://github.com/Cust0mI0")
    print(" ")
    print("---------------------------------------------------------------------------------------")
    print(" ")

def A_NEW_HOPE():
    print(" ")
    print("----------------------------------------------")
    print("                 Episode IV")
    print("                 A new hope")
    print(" ")
    print("         It is a period of civil war.")
    print("         Rebel spaceships, striking")
    print("         from a hidden base, have won")
    print("         their first victory against")
    print("         the evil Galactic Empire.")
    print(" ")
    print("         During the battle, Rebel")
    print("         spies managed to steal secret")
    print("         plans to the Empire's")
    print("         ultimate weapon, the DEATH")
    print("         STAR, an armored space")
    print("         station with enough power to")
    print("         destroy an entire planet.")
    print(" ")
    print("         Pursued by the Empire's")
    print("         sinister agents, Princess")
    print("         Leia races home aboard her")
    print("         starship, custodian of the")
    print("         stolen plans that can save")
    print("         her people and restore")
    print("         freedom to the galaxy.....")
    print(" ")
    print("----------------------------------------------")
    print(" ")

def Once_More_The_Sith_Will_Rule_The_Galaxy():
    print(" ")
    print("----------------------------------------------")
    print(" ")
    print("              Code of the Sith")
    print(" ")
    print("    Peace is a lie. There is only Passion.")
    print("    Through Passion i gain strength.")
    print("    Through Strength i gain Power.")
    print("    Through Power i gain Victory.")
    print("    Through Victory my chains are Broken.")
    print("    The Force shall free me")
    print(" ")
    print("----------------------------------------------")
    print(" ")
